# Numpy: Package for Multidimensional array
## Vector(1d)
### Matrix(2d or 1d)

In [5]:
import numpy as np

In [6]:
# Method 1
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [7]:
# Method 2
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [8]:
list_of_lists=[[1,2,5,3],[4,6,5,6],[7,8,5,9]]
np.array(list_of_lists)

array([[1, 2, 5, 3],
       [4, 6, 5, 6],
       [7, 8, 5, 9]])

In [9]:
np.arange(5,30)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [10]:
np.arange(5,30,3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29])

In [11]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [14]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
np.eye(5).astype(int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [17]:
np.random.rand(2,4)

array([[0.55976848, 0.73908059, 0.49059885, 0.13790408],
       [0.2735171 , 0.14553155, 0.91453701, 0.97467387]])

In [18]:
np.random.randn(2,7)

array([[-0.25427426,  1.45964076, -0.15662758,  1.3081708 , -0.04849151,
        -0.5983309 ,  0.43748799],
       [ 0.44194878,  0.73376712, -0.8387208 ,  0.15377389,  1.45312708,
         0.90253843,  1.39160515]])

In [19]:
np.random.randint(2,10) #random number between 2 and 10 with 10 excluded

8

In [20]:
np.random.randint(20,56,100)

array([51, 40, 55, 27, 20, 47, 33, 41, 20, 42, 27, 47, 46, 38, 44, 46, 42,
       28, 45, 30, 31, 32, 36, 54, 36, 50, 28, 37, 44, 40, 37, 42, 40, 27,
       20, 48, 51, 29, 39, 21, 22, 24, 42, 47, 37, 26, 22, 20, 54, 55, 50,
       20, 47, 48, 22, 34, 25, 29, 35, 49, 30, 30, 20, 45, 25, 32, 20, 39,
       32, 30, 31, 41, 38, 40, 24, 28, 41, 47, 45, 39, 54, 42, 45, 29, 26,
       30, 22, 22, 24, 23, 41, 49, 33, 45, 48, 55, 36, 35, 22, 55])

In [21]:
sample_array=np.arange(30)
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [22]:
rand_array=np.random.randint(0,100,20)
rand_array

array([74, 40, 56, 55, 13, 47, 49, 52, 37, 59, 63, 32, 19, 42, 91, 69, 85,
       94, 25, 50])

In [23]:
sample_array.reshape(3,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [24]:
rand_array.max()      # max element

94

In [25]:
rand_array.argmax()   # index of max element

17

In [26]:
sample_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [27]:
sample_array.shape   #shape gives (row,column)

(30,)

In [28]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [29]:
sample_array.dtype

dtype('int32')

In [30]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [31]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
a=np.random.rand(2,3)
a

array([[0.2920269 , 0.79384099, 0.51105246],
       [0.0549751 , 0.23180153, 0.19236281]])

In [33]:
a.T

array([[0.2920269 , 0.0549751 ],
       [0.79384099, 0.23180153],
       [0.51105246, 0.19236281]])

In [34]:
import numpy as np

In [35]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [36]:
sample_array[8]

18

In [37]:
sample_array[2:5]   #from index 2 to 4

array([12, 13, 14])

In [38]:
sample_array[[2,5]]   #index 2 and 5 individual

array([12, 15])

In [39]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [40]:
sample_array=np.arange(10,21)
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [41]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [42]:
subset_sample_array[:]=1001           # all elememts change to 1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

### Two-Dimensional array

In [43]:
sample_matrix=np.array(([50,20,1,23],[24,23,21,33],[56,76,24,7]))
sample_matrix

array([[50, 20,  1, 23],
       [24, 23, 21, 33],
       [56, 76, 24,  7]])

In [44]:
sample_matrix[0][2]

1

In [45]:
sample_matrix[2,:]      #3rd row

array([56, 76, 24,  7])

In [46]:
sample_matrix[2]         #3rd row

array([56, 76, 24,  7])

### Custom indexing

In [47]:
sample_matrix=np.array(([30,10,1,23],[24,21,32,33],[6,76,24,7]))
sample_matrix

array([[30, 10,  1, 23],
       [24, 21, 32, 33],
       [ 6, 76, 24,  7]])

In [48]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [33, 32],
       [ 7, 24]])

In [49]:
sample_matrix[(2,0),:]

array([[ 6, 76, 24,  7],
       [30, 10,  1, 23]])

In [50]:
sample_matrix[(0,1,2),(2,1,0)]

array([ 1, 21,  6])

###  Selection techniques

In [51]:
sample_array=np.arange(1,31)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [52]:
bool=sample_array<10
bool

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False])

In [53]:
sample_array[bool]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60])

In [55]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08, 4.85165195e+08,
       1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
       7.20048993e+10, 1.95729609e+11, 5.32048241e+11, 1.44625706e+12,
       3.93133430e+12, 1.06864746e+13])

In [56]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
       5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558])

In [57]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738])

In [58]:
np.max(sample_array)

30

In [59]:
np.min(sample_array)

1

In [60]:
np.argmax(sample_array)

29

In [61]:
np.argmin(sample_array)

0

In [62]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676,
       729, 784, 841, 900], dtype=int32)

In [63]:
np.std(sample_array)

8.65544144839919

In [64]:
np.var(sample_array)


74.91666666666667

In [65]:
np.mean(sample_array)

15.5

In [66]:
array=np.random.randn(3,6)
array

array([[-0.91831625, -0.6912169 ,  1.30198818,  0.41267481,  0.06921866,
         1.12138931],
       [ 1.02209681,  0.21509109, -1.02464613,  0.83140716, -0.68636416,
         1.25801858],
       [ 0.27216343, -0.99872092, -0.88076867, -0.71194028, -0.05330428,
        -0.17039325]])

In [67]:
np.round(array,decimals=2)

array([[-0.92, -0.69,  1.3 ,  0.41,  0.07,  1.12],
       [ 1.02,  0.22, -1.02,  0.83, -0.69,  1.26],
       [ 0.27, -1.  , -0.88, -0.71, -0.05, -0.17]])

In [68]:
sports=np.array(['golf','cricket','fball','cricket']) #ascending order
np.unique(sports)

array(['cricket', 'fball', 'golf'], dtype='<U7')

In [69]:
sports=np.array([4,5,3,21,251,0,1,11,4,4,5,21,1]) #ascending order
np.unique(sports)

array([  0,   1,   3,   4,   5,  11,  21, 251])

In [70]:
import pandas as pd
import numpy as np

In [71]:
labels=['w','x','y','z']
list=[10,20,30,40]
array=np.array([10,20,30,40])
dict={'w':10,'x':20,'y':30,'z':40}


In [72]:
pd.Series(data=list)

0    10
1    20
2    30
3    40
dtype: int64

In [73]:
pd.Series(data=list,index=labels)

w    10
x    20
y    30
z    40
dtype: int64

In [74]:
pd.Series(array,labels)

w    10
x    20
y    30
z    40
dtype: int32

In [75]:
pd.Series(dict)

w    10
x    20
y    30
z    40
dtype: int64

### Pandas dataframe and indexing

In [76]:
sports1=pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])
sports1

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [77]:
sports1['cricket']

1

In [78]:
sports2=pd.Series([11,2,3,4],index=['cricket','football','baseball','golf'])
sports2

cricket     11
football     2
baseball     3
golf         4
dtype: int64

In [79]:
sports1+sports2

baseball       NaN
basketball     NaN
cricket       12.0
football       4.0
golf           8.0
dtype: float64

In [80]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H '.split(),columns='Score1 Score2 Score3 Score4 Score5'.split())
df1

Score1    Score2    Score3    Score4    Score5
A  0.711992  0.901177  0.166227  0.189788  0.027468
B  0.891689  0.953360  0.247846  0.993937  0.027991
C  0.728347  0.424431  0.673761  0.004086  0.154801
D  0.315156  0.317043  0.377437  0.913041  0.541190
E  0.533554  0.217412  0.382065  0.572964  0.394433
F  0.813800  0.976584  0.878304  0.485592  0.632293
G  0.108476  0.934659  0.817077  0.396205  0.970232
H  0.106170  0.341480  0.013529  0.903530  0.830923

In [81]:
df1['Score3']

A    0.166227
B    0.247846
C    0.673761
D    0.377437
E    0.382065
F    0.878304
G    0.817077
H    0.013529
Name: Score3, dtype: float64

In [82]:
df1[['Score2','Score1']]

Score2    Score1
A  0.901177  0.711992
B  0.953360  0.891689
C  0.424431  0.728347
D  0.317043  0.315156
E  0.217412  0.533554
F  0.976584  0.813800
G  0.934659  0.108476
H  0.341480  0.106170

In [83]:
df1[['Score2','Score1']]

df1['Score6']=df1['Score1']+df1['Score2']
df1



Score1    Score2    Score3    Score4    Score5    Score6
A  0.711992  0.901177  0.166227  0.189788  0.027468  1.613169
B  0.891689  0.953360  0.247846  0.993937  0.027991  1.845050
C  0.728347  0.424431  0.673761  0.004086  0.154801  1.152778
D  0.315156  0.317043  0.377437  0.913041  0.541190  0.632199
E  0.533554  0.217412  0.382065  0.572964  0.394433  0.750966
F  0.813800  0.976584  0.878304  0.485592  0.632293  1.790383
G  0.108476  0.934659  0.817077  0.396205  0.970232  1.043135
H  0.106170  0.341480  0.013529  0.903530  0.830923  0.447649

In [84]:
df1.drop('Score5',axis=1)  # axis =0 (for index ) & axis = 1 (for columns)



Score1    Score2    Score3    Score4    Score6
A  0.711992  0.901177  0.166227  0.189788  1.613169
B  0.891689  0.953360  0.247846  0.993937  1.845050
C  0.728347  0.424431  0.673761  0.004086  1.152778
D  0.315156  0.317043  0.377437  0.913041  0.632199
E  0.533554  0.217412  0.382065  0.572964  0.750966
F  0.813800  0.976584  0.878304  0.485592  1.790383
G  0.108476  0.934659  0.817077  0.396205  1.043135
H  0.106170  0.341480  0.013529  0.903530  0.447649

In [85]:
df1.reset_index()



index    Score1    Score2    Score3    Score4    Score5    Score6
0     A  0.711992  0.901177  0.166227  0.189788  0.027468  1.613169
1     B  0.891689  0.953360  0.247846  0.993937  0.027991  1.845050
2     C  0.728347  0.424431  0.673761  0.004086  0.154801  1.152778
3     D  0.315156  0.317043  0.377437  0.913041  0.541190  0.632199
4     E  0.533554  0.217412  0.382065  0.572964  0.394433  0.750966
5     F  0.813800  0.976584  0.878304  0.485592  0.632293  1.790383
6     G  0.108476  0.934659  0.817077  0.396205  0.970232  1.043135
7     H  0.106170  0.341480  0.013529  0.903530  0.830923  0.447649

In [86]:
df2={'ID':['101','102','103','107','176'],'Name':['John','Mercy','Akash','Kavin','Lally'],'Profit':[20,54,56,87,123]}
df=pd.DataFrame(df2)
df

ID   Name  Profit
0  101   John      20
1  102  Mercy      54
2  103  Akash      56
3  107  Kavin      87
4  176  Lally     123

In [89]:
df[['ID','Name']]


ID   Name
0  101   John
1  102  Mercy
2  103  Akash
3  107  Kavin
4  176  Lally